id: playbook-CustomIndicatorDemo-test
version: -1
name: playbook-CustomIndicatorDemo-test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: ebdaf3a4-0912-454f-8370-5fb7bfffcb23
    type: start
    task:
      id: ebdaf3a4-0912-454f-8370-5fb7bfffcb23
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '1':
    id: '1'
    taskid: ae5c9730-39fc-4ad7-8478-d20a3fc6a632
    type: regular
    task:
      id: ae5c9730-39fc-4ad7-8478-d20a3fc6a632
      version: -1
      name: test-custom-indicator
      description: This command demonstrates the usage of CustomIndicator.
      script: CustomIndicatorDemo|||test-custom-indicator
      type: regular
      iscommand: true
      brand: CustomIndicatorDemo
    nexttasks:
      '#none#':
      - '3'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '3':
    id: '3'
    taskid: cb6e7515-30f5-4430-8734-ffa4745ba3ce
    type: condition
    task:
      id: cb6e7515-30f5-4430-8734-ffa4745ba3ce
      version: -1
      name: verify outputs
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      yes:
      - '5'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: custom.param1
            iscontext: true
          right:
            value:
              simple: value1
      - - operator: isEqualString
          left:
            value:
              simple: custom.param2
            iscontext: true
          right:
            value:
              simple: value2
      - - operator: isEqualString
          left:
            value:
              simple: Demo.Result.dummy
            iscontext: true
          right:
            value:
              simple: test
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '5':
    id: '5'
    taskid: 246ea808-0fd6-478a-804f-21fb03205b8d
    type: regular
    task:
      id: 246ea808-0fd6-478a-804f-21fb03205b8d
      version: -1
      name: Close
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      closeNotes:
        simple: Test done
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 610,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: Test Playbook to generate CustomIndicator
